- hosts: freeipa
  become: yes
  become_method: sudo
  tasks:
    - name: Install FreeIPA
      import_tasks: 'roles/freeipa/deploy_freeipa_server.yml'
    - name: Setup/Configure FreeIPA users
      import_tasks: 'roles/freeipa/deploy_freeipa_users.yml'
      vars:
        rockyou: "{{ lookup('file', 'conf/freeipa/rockyou.txt').split('\n') }}"