- hosts: manager
  become: yes
  become_method: sudo
  tasks:
    - import_tasks: 'roles/manager/deploy_initial_setup.yml'
    - import_tasks: 'roles/manager/deploy_wazuh_manager.yml'
    - import_tasks: 'roles/manager/deploy_bro_manager.yml'
    - import_tasks: 'roles/manager/deploy_thehive.yml'
    - import_tasks: 'roles/manager/deploy_doorman.yml'
      environment:
        DOORMAN_ENV: prod
