####################################################################
# Set hostname
####################################################################
- name: Set hostname
  command: hostname {{ ansible_ssh_host }}
- command: hostnamectl set-hostname {{ ansible_ssh_host }}
- debug: msg="{{ ansible_ssh_host }}"


####################################################################
# Update system
####################################################################
- name: Update system and add RHEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution == 'CentOS'
- yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_os_family == "RedHat"

###################################################################
# Uninstall any old settings for a FreeIPA server
###################################################################
- name: Uninstall IPA client
  shell: ipa-client-install --uninstall
  ignore_errors: True

###################################################################
# Install/Setup FreeIPA
####################################################################
- name: Install IPA client
  package: name='{{ item }}' state=present
  with_items:
    - vim 
    - freeipa-client 

- name: Run the ipa-server-client command
  command: ipa-client-install -U --domain={{ freeipa_domain }} --hostname={{ ansible_ssh_host }} --server={{ freeipa_hostname }}.{{ freeipa_domain }} --realm={{ freeipa_domain|upper }} --principal={{ freeipa_admin_username }} --password={{ freeipa_admin_password }} --mkhomedir --force-join --force-ntpd
  ignore_errors: True

- name: Ubuntu home dir bug
  shell: "sed -i 's/Default: no/Default: yes/g' /usr/share/pam-configs/mkhomedir"
  when: ansible_distribution == 'Ubuntu'

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up FreeIPA agent on {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
