- name: Set hostname
  command: hostnamectl set-hostname ip-{{ ansible_default_ipv4.address }}

- name: Add Wazuh repo for CentOS and Redhat
  yum_repository:
    name: wazuh_repo
    description: Wazuh agent repo
    enabled: yes
    baseurl: https://packages.wazuh.com/yum/el/$releasever/$basearch
    enabled: yes
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'CentOS'
- yum_repository:
    name: wazuh_repo
    description: Wazuh agent repo
    enabled: yes
    baseurl: https://packages.wazuh.com/yum/rhel/$releasever/$basearch
    enabled: yes
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_os_family == "RedHat" and ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add Wazuh repo for Ubuntu 
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
    - apt-transport-https
    - lsb-release
  when: ansible_distribution == 'Ubuntu'
- shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH > /tmp/wazuh.gpg
- apt_key:
    file: /tmp/wazuh.gpg
    state: present
  when: ansible_distribution == 'Ubuntu'
- command: lsb_release -cs
  register: CODENAME
  when: ansible_distribution == 'Ubuntu'
- apt_repository:
    repo: deb https://packages.wazuh.com/apt {{ CODENAME }} main
    state: present
  when: ansible_distribution == 'Ubuntu'


- name: Install Wazuh
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - libselinux-python
    - wazuh-agent

- lineinfile:
    path: /var/ossec/etc/ossec.conf
    regexp: '<server-ip>'
    line: '    <server-hostname>{{ wazuh_api_domain }}</server-hostname>'

- get_url:
    url: https://raw.githubusercontent.com/wazuh/wazuh-api/2.0/examples/api-register-agent.sh
    dest: /tmp/api-register-agent.sh
    mode: 0755
- lineinfile:
    path: /tmp/api-register-agent.sh
    regexp: 'API_PORT='
    line: 'API_PORT="{{ wazuh_api_port }}"'
- lineinfile:
    path: /tmp/api-register-agent.sh
    regexp: 'API_IP='
    line: 'API_IP="{{ wazuh_domain }}"'
- lineinfile:
    path: /tmp/api-register-agent.sh
    regexp: '^PROTOCOL='
    line: 'PROTOCOL="https"'
- lineinfile:
    path: /tmp/api-register-agent.sh
    regexp: '^USER='
    line: 'USER="{{ wazuh_api_user }}"'
- lineinfile:
    path: /tmp/api-register-agent.sh
    regexp: '^PASSWORD='
    line: 'PASSWORD="{{ wazuh_api_pass }}"'
- name: Register Wazuh API script
  shell: /tmp/api-register-agent.sh
  ignore_errors: True


- name: Enable Wazuh service
  service:
    name: wazuh-agent
    state: restarted
    enabled: yes

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Wazuh agent'
    channel: "{{ slack_channel }}"
