####################################################################
# Install dependencies for Bro
####################################################################
- name: Enable FreeBSD repos
  lineinfile:
    path: /usr/local/etc/pkg/repos/pfSense.conf
    regexp: '^FreeBSD: { enabled: no}'
    line: 'FreeBSD: { enabled: yes}'

- name: Install Bro and dependencies
  shell: pkg add http://pkg.freebsd.org/freebsd:11:x86:64/release_1/All/{{ item }}
  with_items:
    - lua51-5.1.5_9.txz
    - swig-2.0.12_2.txz
    - py27-setuptools-36.0.1.txz
    - py27-sqlite3-2.7.13_7.txz
    - ipsumdump-1.86.txz
    - lbl-hf-1.7.txz
    - lbl-cf-1.2.5.txz

- name: Install/Setup Bro and dependencies
  package: 
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - cmake
    - gmake
    - GeoIP
    - bash   
    - bison  

- name: Install Bro 
  shell: pkg add http://pkg.freebsd.org/freebsd:11:x86:64/release_1/All/{{ item }}
  with_items:
    - broccoli-1.97,1.txz
    - bro-2.4.1_3.txz

- name: Update GeoIP data
  shell: /usr/local/bin/geoipupdate.sh

#- name: Download pfSense-pkg-bro
#  get_url:
#    url: https://github.com/shadonet/pfSense-pkg-bro/files/1248279/pfSense-pkg-bro-2.4.1.zip
#    dest: /tmp/

#- name: Extract pfSense-pkg-bro
#  shell: unzip pfSense-pkg-bro-2.4.1.zip
#  args:
#    chdir: /tmp
    
#- name: Install pfSense-pkg-bro
#  shell: pkg add pfSense-pkg-bro-2.4.1.txz
#  args:
#    chdir: /tmp

- name: Copy Bro configs
  template:
    src: conf/bro/node.cfg
    dest: /usr/local/etc/node.cfg

- name: Start Bro service
  shell: /usr/local/bin/broctl deploy
- shell: /usr/local/bin/broctl start

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Bro and Filebeat on pfSense'
    channel: "{{ slack_channel }}"
