####################################################################
# Logstash configs
####################################################################
- name: Logstash configs for Bro
  template:
    src: conf/logstash/02-beats-input.conf
    dest: /etc/logstash/conf.d/02-beats-input.conf
- template: 
    src: conf/logstash/30-elasticsearch-output.conf
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf

- name: Restart 
  service:
    name: logstash
    state: restarted
    enabled: yes