####################################################################
# Install/Setup Docker
####################################################################
- name: Add Docker repo
  shell: yum install yum-utils -y
- shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- shell: yum makecache fast

- name: Install/Setup Docker
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - docker-ce
    - python-pip

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- pip:
    name: '{{ item }}'
    extra_args: --upgrade
  with_items:
    - docker-py
    - httplib2
    - docker-compose
    - docker

- name: Update docker stuff
  shell: "pip uninstall docker-py; pip uninstall docker; pip install docker"

- name: Start Docekr service
  service:
    name: docker
    state: started
    enabled: yes

####################################################################
# Install/Setup theHive
#################################################################### 
- name: Download theHive git repo
  git: 
    repo: 'https://github.com/CERT-BDF/TheHive.git'
    dest: /opt/TheHive


- name: Start theHive docker container
  shell: docker-compose up -d 
  args:
    chdir: /opt/TheHive/docker/thehive