####################################################################
# Set hostname
####################################################################
- name: Set hostname
  command: hostnamectl set-hostname ip-{{ ansible_default_ipv4.address }}

####################################################################
# Setup NTP
####################################################################
- name: Setup NTP time sync
  package: name="{{ item }}" state=installed
  with_items:
    - ntp
    - ntp-doc
  when: ansible_os_family == "RedHat"
  with_items:
    - ntpd-doc
    - ntpdate
  when: ansible_distribution == 'Ubuntu'

- name: Start NTP daemon
  service:
    name: chronyd
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS'
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
- service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu'

####################################################################
# Update system
####################################################################
- name: Update system and add RHEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution == 'CentOS'
- yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_os_family == "RedHat"

###################################################################
# Uninstall any old settings for a FreeIPA server
###################################################################
- name: Uninstall IPA client
  shell: ipa-client-install --uninstall
  ignore_errors: True

###################################################################
# Install/Setup FreeIPA
####################################################################
- name: Install IPA client
  package: name='{{ item }}' state=present
  with_items:
    - vim 
    - freeipa-client 

- name: Run the ipa-server-client command
  command: ipa-client-install -U --domain={{ freeipa_domain }} --hostname=ip-{{ ansible_default_ipv4.address }} --server={{ freeipa_hostname }}.{{ freeipa_domain }} --realm={{ freeipa_domain|upper }} --principal={{ freeipa_admin_username }} --password={{ freeipa_admin_password }} --mkhomedir --force-join --force-ntpd
  ignore_errors: True