####################################################################
# Seutp/Config users
####################################################################
- name: Create users for env
  ipa_user:
    name: '{{ item }}'
    password: "{{ rockyou|random }}"
    givenname: '{{ item }}'
    sn: Acme
    state: present
    ipa_host: '{{ freeipa_hostname }}.{{ freeipa_domain }}'
    ipa_user: '{{ freeipa_admin_username }}'
    ipa_pass: '{{ freeipa_admin_password }}'
  with_items:
    - furphybogger
    - quaggageggy
    - occiputboggin
    - zaftigpish
    - gazumpchug
    - awkwardfoddered
    - tweezersloaby
    - gongoozledodgy
    - ladidahonk
    - mooseblootered
    - turduckenbox
    - nambypambyhames
    - gristleblimey
    - bumfknackered
    - filletskint
    - ecdysiastsnecky
    - dollopbaffies
    - maverickminger
    - bubblesgutted
    - finaglecraic
    - gubbinsscatter
    - bobbinbolloxology
    - scruffybahoochie
    - ensorcellgowl
    - sousaphonelecky
    - mumpsimusbawbag
    - masticategutties
    - bloviatechuffed
    - britchesporkies
    - rummageshift
    - quokkacannie
    - nincompoopgawk
    - ranivorousbure
    - gazeboloupin
    - skedaddlebaytin
    - logorrheagaff
    - poppysmicdangleberry
    - dudgeonyokes
    - kerfuffledobber
    - goombahgombeen
    - klutzloused
    - crudivoreclarted
    - termitesbawhair
    - sackolagonin
    - manholepuke
    - quibbleglaikit
    - flummoxclart
    - yahookippy
    - fatuousbampot
    - godwotterymardy

- name: Create admin group
  ipa_group:
    name: '{{ freeipa_admin_group }}'
    description: Hackinglab admins
    user: '{{ item }}'
    ipa_host: '{{ freeipa_hostname }}.{{ freeipa_domain }}'
    ipa_user: '{{ freeipa_admin_username }}'
    ipa_pass: '{{ freeipa_admin_password }}'
  with_items:
    - maverickminger
    - gazeboloupin
    - tweezersloaby
    - quibbleglaikit
    - godwotterymardy

- name: Create sudo rule for admins
  ipa_sudorule:
    name: sudo_users
    description: Allow to run every command with sudo
    cmdcategory: all
    hostcategory: all
    usergroup:
      - '{{ freeipa_admin_group }}'
    ipa_host: '{{ freeipa_hostname }}.{{ freeipa_domain }}'
    ipa_user: '{{ freeipa_admin_username }}'
    ipa_pass: '{{ freeipa_admin_password }}'
