####################################################################
# Install Nginx and dependencies
####################################################################
- name: Set SELinux to permissive mode 
  selinux:
    policy: targeted
    state: permissive

####################################################################
# Install Nginx and dependencies
####################################################################
- name : Install dependencies and Nginx
  package: name={{ item }} state=present
  with_items:
    - nginx 
    - mariadb 
    - php 
    - php-fpm 
    - php-common
    - php-mysql 
    - php-gd 
    - php-xml 
    - php-mbstring 
    - php-mcrypt
- service:
    name: php-fpm
    state: restarted
    enabled: yes

####################################################################
# Generate SSL
####################################################################
- file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    state: directory 

- name: Generate DH key
  stat:
    path: /etc/nginx/ssl/dhparam.pem
  register: stat_dhparam
- shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  when: stat_dhparam.stat.exists == False

- name: Create OpenSSL custom cert for Wordpress
  shell: openssl req -new -nodes -x509 -days 3650 -subj "/C=US/ST=NY/L=Rochester/O=None/CN={{ base_domain }}" -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
  when: stat_dhparam.stat.exists == False

####################################################################
# Untar download
####################################################################
- name: Untar Wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /usr/share/nginx/html
    remote_src: yes

####################################################################
# Setup wordpress
####################################################################
- name: Copy wp-config.php
  template:
    src: conf/wordpress/wp-config.php
    dest: /usr/share/nginx/html/wordpress/wp-config.php

- name: Set permissions on Wordpress directory
  shell: chown -R nginx:nginx /usr/share/nginx/html/wordpress
- shell: chmod -R 777 /usr/share/nginx/html/wordpress


####################################################################
# Copy NGINX templates
####################################################################
- name: Backup NGINX config
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- name: Copy Nginx templates
  template:
    src: conf/nginx.conf
    dest: /etc/nginx/nginx.conf

- template:
    src: conf/wordpress/nginx_wordpress.conf
    dest: /etc/nginx/conf.d/nginx_wordpress.conf

####################################################################
# Restart NGINX
####################################################################
- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

####################################################################
# Disable FirewallD
####################################################################
- name: Install/Setup FireallD
  yum:
    name: firewalld
    state: latest
- service:
    name: firewalld
    state: stopped
    enabled: no
