####################################################################
# Install/Setup Postfix and Doveot
####################################################################
- name: Install postfix and dovecot
  package: 
    name: '{{ item }}' 
    state: present
  with_items:
    - postfix
    - dovecot

####################################################################
# Copy config files
####################################################################
- name: Dovecot config
  template:
    src: conf/mail/dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0600'

- name: Postfix config
  template:
    src: conf/mail/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0600'

####################################################################
# Start services
####################################################################
- name: Start Dovecot and postfix
  service: 
    name: '{{ item }}' 
    state: restarted
  with_items:
    - postfix
    - dovecot

####################################################################
# Disable FirewallD
####################################################################
- name: Install/Setup FireallD
  yum:
    name: firewalld
    state: latest
- service:
    name: firewalld
    state: stopped
    enabled: no

       